### ISSUE TITLE
Type conversion

### ISSUE THREAD

**Issue by miljan-aleksic** [pablohpsilva/vuejs-component-style-guide#1]
Thank you for the guide, it will definitely help.

In the [Why](https://github.com/pablohpsilva/vuejs-component-style-guide#how-5) of **Harness your component options** states `Use type conversion to cast option values to expected type`. As Vue doesn't support props conversions, I must assume the conversion is expected to be done by a computed property or when used. It would be interesting to put some more words and example of best practice about it.

**Comment by pablohpsilva** [comment]
Thank you @miljan-aleksic ! I'll update it soon.
What I was trying to say was to use what vue called "prop validation". Things like: 
```
props: {
  max: {
    type: Number, // This "type" attribute
  },
}
```

Thank you very much for your help! I'll update it soon enough.

**Comment by pablohpsilva** [comment]
Please @miljan-aleksic , check the README.md again, please.
If it's all good, let me know and I'll either close this isse or fix the README.md again.

**Comment by miljan-aleksic** [comment]
@pablohpsilva, now it's clear, tks :)

I think you can remove the [2*] and the example comment, besides no existing a pre [1*] anywhere the docs are straightforward about it.

**Comment by pablohpsilva** [comment]
You're welcome @miljan-aleksic !! Again, thank you for this issue.

I will keep the changes for now and soon I'll highlight the parts where the "Why" is connected to the "How". I think it will help and solve most of the possible doubts. 

Thank you for this issue and great idea! :D
