### ISSUE TITLE
Remove use-component-name-as-style-scope

### ISSUE THREAD

**Issue by franciscolourenco** [pablohpsilva/vuejs-component-style-guide#18]
I would say this section is opinionated outside of the scope of Vue components, into a field of CSS which is controversial. It advises BEM and OOCSS which are methodologies which some people choose not to subscribe to knowingly.

Also exemplifies a kind of nesting one should probably avoid for a few reasons: `MyCompoennt li {}`

Also advises to use both `<style scoped>` along with css scoping, without explaining any substantial benefit.

https://github.com/pablohpsilva/vuejs-component-style-guide#use-component-name-as-style-scope

**Comment by yzb162534** [comment]
In our project, we always use component name as componet's root class.
We think it is useful to locate the component in html.

**Comment by franciscolourenco** [comment]
@yzb161114 that makes total sense. What doesn't make a lot of sense is to recommend nesting css selectors AND using <style scoped>. Maybe you shouldn't nest at all because of increased specificity.

**Comment by pablohpsilva** [comment]
Hello @aristidesfl ! :D 

I see... Well, I think using BEM and/or OOCSS will guarantee the component will always have a specific context. This section is there just to put two good practices together and make good use of them while building components.

I know that `<style scope>` will address that issue cleverly, but I think  That's a good way of separating things in components.

Anyhow, please, make a PR changing what you see fit and let's talk about it.

Thank you again for your help @aristidesfl and @yzb161114

**Comment by pablohpsilva** [comment]
I will close this issue for now. It will be reopened when someone else has anything else to add about this matter.

Thank you @aristidesfl and @yzb161114! You guys rock! :D

**Comment by franciscolourenco** [comment]
Besides the readability issues which could result from the nesting:

- Those css methodologies are outside of the main topic of the guide (if you want to keep it focused).
- They compete with functionality offered by Vue. Vue doesn't require/benefit from that specific practice.
- There are other places where people can read about available CSS methodologies more thourougly and make up their mind. As far as I've seen the opinions on this topic remain very scattered.
- It takes advantage of a guide about one technology to promote another.
- It might end up antagonising people who disagree with such CSS practices, and would otherwise follow the rest of the guide.

Didn't make a PR because I would be removing something you wrote, so.. its up to you take it out if you think this point of view makes sense. Cheers!
