### ISSUE TITLE
Docute docs translation links are broken 

### ISSUE THREAD

**Issue by shershen08** [pablohpsilva/vuejs-component-style-guide#22]

**Comment by pablohpsilva** [comment]
Thank you @shershen08 ! I'll fix them ASAP.

**Comment by pablohpsilva** [comment]
I removed it until fixed. Than you once again @shershen08

**Comment by shershen08** [comment]
Yes, I agree it's better like this for now.

**Comment by shershen08** [comment]
Afaik that's one of the options to impl multilingual in Docute -  https://docute.js.org/#/home?id=navbar

**Comment by pablohpsilva** [comment]
Fixed! Finally. Sorry for taking so long =X
