### ISSUE TITLE
About watch and methods

### ISSUE THREAD

**Issue by StevenYuysy** [pablohpsilva/vuejs-component-style-guide#25]
```JavaScript
// methods
watch: {}.
methods: {}
```

My question is, `watch` supposed to be a watcher instead of `methods`.
It would be better change to 

``` JavaScript
// watch and methods
watch: {},
methods: {}
```

**Comment by pablohpsilva** [comment]
Hello @StevenYuysy ! How are you doing? Thank you for this issue.

What the style guide meant was that both `watch` and `methods` look, feel and produce methods (against `computed`, for example, that look, fell like a method but produce a variable). The comment `// methods` is just telling you should keep methods grouped.

**Comment by StevenYuysy** [comment]
Thx for your explanation.
