### ISSUE TITLE
Directory Structure Patterns

### ISSUE THREAD

**Issue by seanbuscay** [pablohpsilva/vuejs-component-style-guide#42]
Hello.  

It is great to have found your style guide.  

While learning Vue I found it is flexible; allowing multiple ways to accomplish the same functionality.  The flexibility also presents a challenge when trying to determine which approach to take.

Your approach of using Why/How to describe a uniform set of patterns is excellent.  Thank you.

Having read your explanations for the directory structure in your recent post regarding the vue-material-boilerplate, I'd like to suggest adding a version of it to this style guide.

Thanks again.  I found your style guide yesterday while looking for tips on a good directory structure and then today saw your post.  Both helped answer my questions.

**Comment by pablohpsilva** [comment]
Hello @seanbuscay ! Thank you! :D 

You're very much welcome. 

About the directory structure pattern I think we can talk about it. This will be written by all of us.
In the current moment I'm working a lot. But soon I'll come back to you about this issue, OK?

**Comment by pablohpsilva** [comment]
Hello @seanbuscay ! Sorry for making you wait for so long.

I also think the vue-material-boilerplate directory structure is very good. I'm using it in several large scale apps nowadays and devs are liking it. There's another one from [Nuxt](https://nuxtjs.org/guide/directory-structure). Have you heard about it?

**Comment by seanbuscay** [comment]
I'll check it out. Thank you.

**Comment by pablohpsilva** [comment]
@seanbuscay I'll close this issue for now. Reopen it when you want.

Thank you once again :D

**Comment by wosubtil** [comment]
Before anything congratulations @pablohpsilva . Your guide has an incredible quality! 

I don't know if it fits to quote in this "issue" or create a new one, but one thing that I miss is a reference about the organizations of resources and components of the app.

When I used to develop in Angular 1x, I used the styleguide do John Papa, and in it there is a topic about this point: https://github.com/johnpapa/angular-styleguide/blob/master/a1/i18n/pt-BR.md#application-structure

I wonder if you think is good  create a topic in the styleguide about this possible resource?

**Comment by pablohpsilva** [comment]
Hello @welintonti ! Thank you dude! :D 
Well... since this is a recurrent request, could you please open an issue for it and link this issue?
I much appreciate it.

**Comment by nxpatterns** [comment]
great suggestions are always welcome, some hints:

* http://pksunkara.com/posts/complex-vuejs-app-structure/
* https://nuxtjs.org/guide/directory-structure#directories
* https://medium.com/3yourmind/large-scale-vuex-application-structures-651e44863e2f
* https://forum.vuejs.org/t/structuring-very-large-applications/840

It should be maybe a section at https://github.com/vuejs/awesome-vue something like "recommended big vue project structure"
