### ISSUE TITLE
Section "Assign this to component" example does no show it

### ISSUE THREAD

**Issue by etiennellipse** [pablohpsilva/vuejs-component-style-guide#43]
This section stipulates this:

> assigning this to a variable named component the variable tells developers it's bound to the component instance wherever it's used.

The code example attached does not define any variable named component. It's confusing.

**Comment by Elfayer** [comment]
Right.

And I'd add a mention to explain that in ES6 you don't need anything like `var self = this`. But in ES5 you will.

**Comment by etiennellipse** [comment]
Well, you don't need it when using arrow functions, since the lexical scope is kept. But you might if you are using a typical `function` for whatever reason.

**Comment by pablohpsilva** [comment]
What do you think about this edit:
---
[...]
In other words: Do **NOT** code things like `var self = this;` anymore if you're using **ES6**. You're safe using Vue components.

### Why
* Using ES6, there's no need to save `this` to a variable;
* In general, when using arrow functions the lexical scope is kept
* If you're **NOT** using ES6 and, therefore, not using `Arrow Functions`, you'd have to add `this` to a variable. That's the only exception.

[...]

**Comment by Elfayer** [comment]
@pablohpsilva Sounds good to me!

Just some few points:

- `const` is ES6, so I'd write `var self = this;`, on the first line.
- Be consistent, write **NOT** in capital the "why" section.

**Comment by Elfayer** [comment]
[out of topic]
Congrats for the 1000 stars! ;)

**Comment by pablohpsilva** [comment]
Done guys! Thank you so much! :D 

Thank you @Elfayer hehehehe
