### ISSUE TITLE
Component naming section is confusing to me

### ISSUE THREAD

**Issue by thedamon** [pablohpsilva/vuejs-component-style-guide#53]
Particularly this sentence: _"**app- namespaced:** if very generic and otherwise 1 word, so that it can easily be reused in other projects."_

Very generic components should have "app" as a namespace? Or should they have your app's name as a namespace ("myapp-")? Or is it using app as a namespace because in the example it is descriptive ( _app-header_ for the header of the app)

Couldn't very generic components be easily used elsewhere? It sounds like it's saying to app-namespace things if they're very generic and otherwise make them one word, but this sentence could be read in 2 different ways.

Am I supposed to literally add `app-` in front of all components that are 1 word AND generic and not to any other ones?

I'm happy to try and clarify this if I can make it make sense to myself :)

**Comment by pablohpsilva** [comment]
Hello @thedamon :D 
First things first: Thank you for opening this issue :D 

What it meant was add `myapp-`, like the name of your application.

If you can create a PR with the changes, that would be awesome!

**Comment by mikeerickson** [comment]
+1
