### ISSUE TITLE
中文翻译中的一个小错误

### ISSUE THREAD

**Issue by alwxkxk** [pablohpsilva/vuejs-component-style-guide#66]
位置：Component event names
Events should either end in verbs in the infinitive form (e.g. client-api-load) or nouns (e.g drive-upload-success) (source);
事件命名应该以动词（如 client-api-load） 或是 形容词（如 drive-upload-success）结尾。
形容词 应为 名词。

**Comment by pablohpsilva** [comment]
Hello @alwxkxk 
I translated it but I didn't understand this issue (most likely to be the bad translation). Could you write in English? Even better, could you make a PR?

**Comment by alwxkxk** [comment]
PR: https://github.com/pablohpsilva/vuejs-component-style-guide/pull/68
