### ISSUE TITLE
Component's name in folder

### ISSUE THREAD

**Issue by andreevsm** [pablohpsilva/vuejs-component-style-guide#67]
As you can see below, i have a question... How correctly to name components here?
![image](https://user-images.githubusercontent.com/26060516/34336980-b68eac42-e96c-11e7-9b8c-7bf58dce1858.png)

**Comment by serzhikkk** [comment]
Oh, sorry, the answer was here 
https://ru.vuejs.org/v2/guide/components.html#%D0%A1%D0%BE%D0%B3%D0%BB%D0%B0%D1%88%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BF%D0%BE-%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8E-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2

**Comment by pablohpsilva** [comment]
Hello @serzhikkk 
I would name the file just like I name the component:
`ComponentOne.vue`
