### ISSUE TITLE
'Keep component props primitive' - typos in sample code

### ISSUE THREAD

**Issue by apdevelop** [pablohpsilva/vuejs-component-style-guide#70]
Sample code in the [Keep component props primitive](https://github.com/pablohpsilva/vuejs-component-style-guide#keep-component-props-primitive) section contains several typos:
```
<range-slider
  :values="[10, 20]"
  min="0" <!-- Should be :min="..." for evaluating as JS expression to Number -->
  max="100" <!-- Should be :max="..." for evaluating as JS expression to Number -->
  step="5"  <!-- Should be :step="..." for evaluating as JS expression to Number -->
  :on-slide="updateInputs"   <!-- Should be @on-slide="..." -->
  :on-end="updateResults"> <!-- Should be @on-end="..." -->
</range-slider>
```
See also [Literal vs. Dynamic](https://vuejs.org/v2/guide/components.html#Literal-vs-Dynamic)

**Comment by pablohpsilva** [comment]
Thank you @apdevelop ! Can you create a PR with the corrections?

**Comment by apdevelop** [comment]
Done it!  https://github.com/pablohpsilva/vuejs-component-style-guide/pull/75

**Comment by pablohpsilva** [comment]
Thank you once again! :D
